### ISSUE TITLE
[Question] fork?

### ISSUE THREAD

**Issue by ngortheone** [AbhimanyuHK/aws-psycopg2#1]
This looks like a fork of
https://github.com/jkehler/awslambda-psycopg2
(or vice-versa)

If yes - what are main differences? I am currently using https://github.com/jkehler/awslambda-psycopg2 but I can't find it on PyPI. So I am trying to figure out if I can substitute it with this package?

Thanks

**Comment by AbhimanyuHK** [comment]
This is not the fork of https://github.com/jkehler/awslambda-psycopg2.

Forked from https://github.com/psycopg/psycopg2 and compiled
