### ISSUE TITLE
Package creates files too big to allow Lambda in-line editing

### ISSUE THREAD

**Issue by wellsoliver** [AbhimanyuHK/aws-psycopg2#13]
Maybe something we'd need to accept, though I've used a AWS compiled pscopg2 package before, but this creates a 35MB directory. When you zip this and copy it to AWS Lambda, the package is too large to allow in-line code editing, which is a super useful feature in the environment. I believe the max might be 3-5MB.

[I have used this project](https://github.com/jkehler/awslambda-psycopg2) which creates a much smaller package and allows for in-line editing, like 1.5MB.

Again, not sure if you can work around this but I thought I'd mention re: overall usability.

**Comment by AbhimanyuHK** [comment]
Hey @wellsoliver, create lambda layer & map to lambda function 

refer : https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by wellsoliver** [comment]
hey, didn't know about layers! Thanks!
