### ISSUE TITLE
"module 'psycopg2' has no attribute 'errors"

### ISSUE THREAD

**Issue by jcuna** [AbhimanyuHK/aws-psycopg2#2]
Not sure if this is because there's an issue with the psycopg2 version compiled in this package. I saw this issue opened for psycopg2 some time ago and a few other psycopg2 library spin offs. In short one can not reference psycopg2.errors.*

**Comment by AbhimanyuHK** [comment]
which version are you using?

**Comment by AbhimanyuHK** [comment]
[1.2.1](https://pypi.org/project/aws-psycopg2/1.2.1/) is solving this issue.

`import psycopg2.errors as e`
