### ISSUE TITLE
ImportError: libpq-3d107b13.so.5.11

### ISSUE THREAD

**Issue by Sviat** [AbhimanyuHK/aws-psycopg2#3]
Version 1.2.0 released 5 hours ago is actually broken.

`
    from psycopg2 import DatabaseError
.eggs/aws_psycopg2-1.2.0-py3.7.egg/psycopg2/__init__.py:50: in <module>
    from psycopg2._psycopg import (                     # noqa
E   ImportError: libpq-3d107b13.so.5.11: cannot open shared object file: No such file or directory
`
1.1.1 worked and still works fine.

**Comment by jcuna** [comment]
Any news on this?

**Comment by AbhimanyuHK** [comment]
Thank you for the report @Sviat 
We will address the issue soon.

**Comment by AbhimanyuHK** [comment]
Try [1.2.1](https://pypi.org/project/aws-psycopg2/1.2.1/), This may help.

**Comment by adnmonroy** [comment]
Solution for me: Compress using 7-Zip. Windows zip tool cause error.
