### ISSUE TITLE
errorMessage": "Unable to import module <<<myhandler name>>>> .No module named <<<myhandler name>>>>

### ISSUE THREAD

**Issue by swathichitra15** [AbhimanyuHK/aws-psycopg2#5]
I deployed my lambda into aws environment. Had aws-psycopg2==1.2.1 in my requirements.txt and had import psycopg2 in my python code. When pip install happened in my linux environment, it actually added all the below binaries and when I invoke my lambda I get my handler itself is not found.

adding: psycopg2/ (stored 0%)
05:15:36   adding: psycopg2/_psycopg.cpython-37m-darwin.so (deflated 66%)
05:15:37   adding: psycopg2/_psycopg.cpython-37m-i386-linux-gnu.so (deflated 64%)
05:15:37   adding: psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so (deflated 70%)
05:15:37   adding: psycopg2/_psycopg.cpython-34m.so (deflated 70%)
05:15:37   adding: psycopg2/_psycopg.cpython-35m-darwin.so (deflated 66%)
05:15:37   adding: psycopg2/_psycopg.cpython-36m-i386-linux-gnu.so (deflated 64%)
05:15:37   adding: psycopg2/_json.py (deflated 64%)
05:15:37   adding: psycopg2/errorcodes.py (deflated 65%)
05:15:38   adding: psycopg2/_psycopg.cpython-37m-x86_64-linux-gnu.so (deflated 69%)
05:15:38   adding: psycopg2/sql.py (deflated 71%)
05:15:38   adding: psycopg2/errors.py (deflated 45%)
05:15:38   adding: psycopg2/_psycopg.cpython-35m-x86_64-linux-gnu.so (deflated 70%)
05:15:38   adding: psycopg2/_psycopg.cpython-35m-i386-linux-gnu.so (deflated 64%)
05:15:38   adding: psycopg2/tz.py (deflated 60%)
05:15:38   adding: psycopg2/.dylibs/ (stored 0%)
05:15:39   adding: psycopg2/.dylibs/libcrypto.1.1.dylib (deflated 53%)
05:15:39   adding: psycopg2/.dylibs/libpq.5.11.dylib (deflated 56%)
05:15:39   adding: psycopg2/.dylibs/libssl.1.1.dylib (deflated 58%)
05:15:39   adding: psycopg2/_ipaddress.py (deflated 56%)
05:15:39   adding: psycopg2/_psycopg.so (deflated 69%)

**Comment by AbhimanyuHK** [comment]
This is not related to this library @swathichitra15 

Please refer: [aws-lambda-unable-to-import-module-lambda-function](https://stackoverflow.com/questions/49734744/aws-lambda-unable-to-import-module-lambda-function)
