### ISSUE TITLE
Support for Python 3.9 and ARM64 architectures

### ISSUE THREAD

**Issue by alexanderluiscampino** [AbhimanyuHK/aws-psycopg2#8]
Hi,

Wondering the support on this project. And if possible to add the python 3.9 and ARM63 arhcitectures?

**Comment by basitiyidir** [comment]
looking forward to python 3.9

**Comment by AbhimanyuHK** [comment]
Hey @alexanderluiscampino @basitiyidir @davidela 

Here is the new build [1.3.0](https://pypi.org/project/aws-psycopg2/1.3.0/)

Let me know if guys face any issues

thanks for waiting.........

**Comment by AbhimanyuHK** [comment]
wait for sometimes i'm testing it.

**Comment by AbhimanyuHK** [comment]
Hi Guys.

Here is the latest build https://pypi.org/project/aws-psycopg2/1.3.8/

Many Thanks for waiting

**Comment by GabriFila** [comment]
Hi @AbhimanyuHK thank you for this package

I tried using this on a `Macbook Pro M2 max` with `Python 3.9` but it throws me this error:


> ```
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/gabrifila/.virtualenvs/wwm-core/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/gabrifila/.virtualenvs/wwm-core/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/gabrifila/.virtualenvs/wwm-core/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (no such file), '/Users/gabrifila/.virtualenvs/wwm-core/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```



I'm using version `1.3.8` in the `requirements.txt`. 

Do you know if it is possible to use it in this situation and do you have any suggestions on how to fix?

Thank you
